modmark-org/modmark

- cli/Cargo.toml
- cli/src/main.rs
- Resolves: GH-13.
Uses clap for the cli, currently takes positional arguments for input and output file. Termion is used prettify and improve UX. This also implements a -w flag that supports compilation on save. Also implements -d for development mode which prints the tree on compilation
> GH-13: Create cli base with watching.

- .github/workflows/RustCI.yml
> GH-30: Remove lint from CI

- cli/Cargo.toml
- cli/src/main.rs
> GH-24: Make terminal output work for windows

- README.md
> GH-17: Add cli run instructions to README

- playground/static/index.html
GitHub should have a capitalized H
> GH-34: Change to GitHub from Github

- cli/Cargo.toml
- cli/src/error.rs
- cli/src/main.rs
- cli/src/package.rs
- Resolves: GH-20.
Some things became apparent during development: and will be split into new issues
- Standard libraries should be handled by core directly #47
- Downloading of cached packages is put on hold until further #48
> GH-20: Add package management for local and cache

- MODMARK.md
- REFERENCE.md
Resolves: GH-29
This adds a reference document for tags and smart punctuation in ModMark, as well as a description of its concepts and functionality. These documents will likely be updated later on to match changes and developments in the language.
> GH-29: Add syntax documentation

- core/build.rs
This PR changes the `Command` from using `.output()` (which blocks the thread until the program is finished) to using `.spawn()` (which spawns the process without blocking), and then loops through all spawned threads and waits. This builds the modules in parallel.
Resolves #74
> GH-74: Build modules async

- core/build.rs
Resolves: #89 
This PR adds warnings in the build script for when modules fail to build.
> GH-89: Add build script warnings for failed modules builds

- cli/src/error.rs
- cli/src/main.rs
> GH-81: Infer output format based on file extension

- cli/Cargo.toml
- cli/src/main.rs
> GH-53: Keep context alive when using --watch flag

- modules/html/src/main.rs
> GH-102: Remove trailing comma in transform_heading

- parser/src/lib.rs
- parser/src/module.rs
- parser/src/punct.rs
- parser/tests/compilation_tests/leading_rows_paragraph.mdmtest
- parser/tests/compilation_tests/multiline_module.mdmtest
- parser/tests/compilation_tests/trailing_rows_paragraph.mdmtest
Resolves GH-106 and the problems described in there, as well as adding some tests that verifies that the fixes work correctly, and some small general improvements in the parser.
> GH-106: Fix various bugs in parser

- playground/static/main.js
> GH-136: Clear selection on transpile-other

- core/src/context.rs
This PR fixes the inconsistent error type when you have a missing transform. #145 outlines how an unknown module expression without arguments would give an "No package for transforming..." error while making that same expression with arguments would give another error. This PR fixes it so that it always yields "No package for transforming..."-error regardless of if arguments are supplied or not.
Moreover, this touches on #125 since the error originated from that it was possible to serialise JSON for non-existing modules, assuming they had no arguments. The example in #125 will no longer produce valid JSON, since Core would impossibly know what to name unnamed arguments when constructing the map. #125 will thus have an outcome other than the one suggested, but the inconsistencies will be …
> GH-145: Fix inconsistent error on missing transform

- cli/src/main.rs
This PR makes the Cli write out any CoreError when running with the `--watch` flag rather than terminating the program. See screenshot:
- Resolves GH-156
> GH-156: Print CoreError in the Cli when running in Watch mode

- packages/html/src/main.rs
> Fix styling on the html  __error module

- packages/layout/src/main.rs
- packages/layout/tests/newline_html.json
- packages/layout/tests/newline_latex.json
- packages/layout/tests/newpage_html.json
- packages/layout/tests/newpage_latex.json
Resolves GH-162. Adds the `[newline]` and `[newpage]` modules in the layout package, I'm open to other name suggestions.
> Add modules for producing line and page breaks

- README.md
> GH-165: Remove "No Chromium support" text from Readme

- Cargo.toml
- core/src/std_packages.rs
- packages/link/Cargo.toml
- packages/link/src/main.rs
- packages/link/tests/html_test_label.json
- packages/link/tests/html_test_nolabel.json
- packages/list/Cargo.toml
- packages/list/src/lib.rs
- packages/list/src/main.rs
- packages/list/tests/test_basic_list_html.json
Resolves #59 and #61 by adding a list and link package. There is only HTML support as of now, so if this gets merged issues for adding LaTeX support should be created. Probably should have split this up into two PRs but the link package was so small I just kept going, if it is a big deal I can split it up now. Could have made the commits reference the larger issues (#57) instead maybe, not sure how to work with small issues in the best way.
Please test the packages to make sure they are working, I have been sick and tired when finishing up :p
- Resolves #59
- Resolves #61
> GH-61: Add link and list package

- cli/Cargo.toml
- cli/src/error.rs
- cli/src/main.rs
- cli/src/package.rs
- core/Cargo.toml
- core/src/lib.rs
- playground/web_bindings/Cargo.toml
- playground/web_bindings/src/lib.rs
- Resolves: GH-48
- Resolves: GH-52
> GH-48: Add package managment via registry

- core/src/context.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/std_packages_macros.rs
- playground/static/main.js
- playground/static/style.css
> GH-161: Add support for transform description in manifest

- packages/latex/src/main.rs
- packages/latex/tests/test_document.json
- packages/link/src/main.rs
- packages/link/tests/latex_test_label.json
- packages/link/tests/latex_test_nolabel.json
> GH-115: Add latex support for links

- core/src/element.rs
- core/src/error.rs
> GH-177: Give error on config module past the parsing step

- parser/src/module.rs
- parser/tests/compilation_tests/invocation_corner_cases.mdmtest
Resolves GH-183. This PR also includes tests for these new corner-cases
> GH-183: Relax restrictions for argument value parsers

- core/src/fs.rs
> GH-201: Avoid unwraps in read_file and create_file

- packages/link/src/main.rs
> GH-192: Add internal referencing

- packages/files/src/main.rs
This gives a compilation warning if an alt-text isn't given. It also escapes quotes and other characters that should be escaped in HTML (using `__text`)
Resolves GH-227
> GH-227: Add alt-text to image

- cli/src/error.rs
- cli/src/main.rs
- cli/src/package.rs
- core/src/package_store.rs
- playground/web_bindings/src/web_resolver.rs
Resolves GH-203 by renaming registry into catalog and switch the `pkgs:` specifier to `catalog:`
> Rename "registry" to "catalog"

- README.md
- cli/Cargo.toml
- cli/README.md
- cli/src/file_access.rs
- cli/src/main.rs
- cli/src/package.rs
- Resolves: GH-178.
Adds functionality to:
* List cached packages
* Clear cache
* Print location of cache
> GH-178: Add CLI subcommand for handling cache

- cli/src/main.rs
- core/src/context.rs
- core/src/lib.rs
Resolves GH-246. I added a `--verbose` flag as @CMDJojo suggested! : )
> Disable verbose errors and add --verbose CLI flag 

- core/src/package_store.rs
> GH-262: Change package order to external, standard and then native packages

- .github/workflows/DeployPreview.yml
> GH-268: Change concurrency group to include github.event.number

- packages/flow/src/main.rs
> GH-272: Fix case-sensitive check for if-const

- core/src/package.rs
This is connected to issue #198 only for imports/reading manifest. When creating a ZIG package I kept getting the error when importing a package despite not doing anything other than printing a manifest to stdout. An equivalent package in Rust had no problems, I also checked to see that they printed identical json.
With the early exits as in issue #198 I read that it could be because the call stack not being emptied but I have not had a lot of luck finding information on the issue. When googling again for this issue I found https://github.com/wasmerio/wasmer/issues/2566 which seems to describe the problem we have. It seems like the issue is with the Rust create API and that the way it uses error is more like a message.
> GH-198: Ignore WASI errors during import if exit code was 0

- core/src/context.rs
- core/src/package.rs
This changes the string comparison for checking exit code 0 to an attempt at downcasting to WasiError::Exit. Resolves GH-285
> GH-285: Check WasiError::Exit(0) instead of string comparison

- packages/code/src/main.rs
- packages/code/tests/test_defaults_latex.json
- packages/code/tests/test_inline_latex.json
- packages/code/tests/test_java_latex.json
Resolves: GH-113
Adds support to the code module for latex
> Add latex support to the code module

- packages/html/src/main.rs
> GH-290: Add support for verbatim tags in HTML

- packages/code/src/main.rs
- packages/code/tests/test_defaults_latex.json
- packages/code/tests/test_java_latex.json
- playground/web_bindings/Cargo.toml
This PR resolves GH-298 and resolves GH-299
*Edit*: Resolves GH-301
> Improve code module

- packages/list/src/lib.rs
- packages/list/src/main.rs
- packages/list/tests/test_basic_list_html.json
Resolves GH-296, and also does some small other general improvements
> GH-296: Use inline-content for list items

- cli/src/error.rs
- cli/src/main.rs
- cli/src/templates.json
> GH-287: Add subcommand for initialising package code skeletons

- packages/link/src/main.rs
- packages/link/tests/latex_test_label.json
- packages/link/tests/latex_test_nolabel.json
> GH-317: Use inline_content for LaTeX URL labels

- packages/table/src/main.rs
- packages/table/tests/test_all_border_html.json
- packages/table/tests/test_all_border_latex.json
- packages/table/tests/test_big_table.json
- packages/table/tests/test_caption_html.json
- packages/table/tests/test_caption_label_html.json
- packages/table/tests/test_caption_label_latex.json
- packages/table/tests/test_caption_latex.json
- packages/table/tests/test_heading_html.json
- packages/table/tests/test_heading_latex.json
- packages/table/tests/test_horizontal_border_html.json
- packages/table/tests/test_horizontal_border_latex.json
- packages/table/tests/test_label_html.json
- packages/table/tests/test_label_latex.json
- packages/table/tests/test_mixed_alignment_html.json
- packages/table/tests/test_mixed_alignment_latex.json
- packages/table/tests/test_no_strip.json
- packages/table/tests/test_outer_border_html.json
- packages/table/tests/test_outer_border_latex.json
- packages/table/tests/test_right_alignment_html.json
- packages/table/tests/test_right_alignment_latex.json
- packages/table/tests/test_strip.json
- packages/table/tests/test_vertical_border_html.json
- packages/table/tests/test_vertical_border_latex.json
> GH-326: Remove raw! macro and use inline_content for caption

- packages/table/src/main.rs
- packages/table/tests/test_big_table.json
- packages/table/tests/test_caption_html.json
- packages/table/tests/test_caption_label_html.json
> GH-328: Fix closing tag and update tests

- packages/link/src/main.rs
> GH-332: Add [target]

- website/src/Playground.tsx
Resolves: GH-338
Fixes issue where open in overleaf remvoes newlines
> GH-338: Fix newline issue with open in overleaf button

- website/src/Playground.tsx
> GH-345: Set default preview mode to rendered-html-iframe

- website/src/Homepage.tsx
> GH-353: Add link to bachelor thesis in learn more bubble

- licenses.txt
> GH-348: Update licenses.txt

- website/src/Guide.tsx
- website/src/GuidePage.tsx
- website/src/Playground.tsx
- website/src/main.tsx
This PR resolves #303 by adding a guide to the webpage.
> GH-303: Add a guide to the website

- website/src/Homepage.tsx
- website/src/PackageDocsPage.tsx
Resolves GH-302. Not perfect, but a few quick and small improvements to the mobile layout of the homepage.
> GH-302: Improve mobile layout

- website/src/Playground.tsx
- website/src/main.tsx
> Fix preview prompt height issue

- core/src/context.rs
> GH-372: Add #[serde(default)] to parent args

- website/src/Playground.tsx
> GH-360: Check for compilerLoaded before showing file tree

- website/src/Guide.tsx
- website/src/GuidePage.tsx
- website/src/Homepage.tsx
- website/src/PackageDocs.tsx
- website/src/PackageDocsPage.tsx
- website/src/Playground.tsx
- website/src/main.css
- website/src/main.tsx
This PR resolves GH-366 by setting background-color on our HTML page to `#f1f1f1`, which makes it better-looking, especially on Safari
> Set background-color

- cli/src/main.rs
> File watcher only cares about assets

- packages/bibliography/src/main.rs
- packages/bibliography/tests/test_bibliography_unused_shown_latex.json
> GH-381: Use [target] for LaTeX specialization
