modmark-org/modmark

- core/src/lib.rs
- parser/src/lib.rs
- playground/index.html
- playground/web_bindings/src/lib.rs
This PR contains some improvements to the playground and the document tree first written by @adelhult , see GH-6 for the initial pull request. The changes were focused on making the initial tree look more like what might appear in the final product.
The project structure remains the same as implemented by @adelhult , however some internal restructurings were made: 
First of all, the `Element` enum now only has two cases, `Data(String)` and `Node{name: String, attributes: [String:String], children: [Element]}`, instead of the previous three, `Document(Box<Self>)`, `Paragraph(Box<Self>)` and `Text(String)`. Since the tree should be sent to and from different WASM-modules dynamically, it isn't possible to know the different possible nodes before-hand. Now, we have one leaf node, …
> Resolve GH-5: Improve playground and initial AST

- .github/workflows/DeployPages.yml
This PR contains a workflow for building and deploying the Playground to GitHub Pages on pushes to the `main` branch.
As a result of GH-5, we created a playground site which, in the current state, is a simple HTML page with an input box, which then uses simple JS to compile that input using our library and display either the parsed document tree or the output HTML. Together with the build instructions provided in the `playground` subdirectory, this is useful to visualize progress of our parser and tree model, and is an useful tool for development.
As a natural next step, GH-9 was created to automatically deploy this playground site to GitHub Pages. As discussed in GH-5, other markup languages such as Djot also have a [playground](https://www.djot.net/playground/), and it is very likely …
> Add automatic deployment of Playground to GitHub Pages

- .github/workflows/RustCI.yml
This PR adds the `--no-fail-fast` flag to `cargo test` to continue running tests even if one test fail.
> GH-3: Add --no-fail-fast flag to continue test on fail

- .github/workflows/DeployPages.yml
- .github/workflows/RustCI.yml
This PR adds the wasm32-wasi target to the toolchains for both CI and Deploy to be able to compile and build WASI modules
> GH-3: Add wasm32-wasi target to toolchain for modules

- .github/workflows/DeployPages.yml
- .github/workflows/RustCI.yml
This adds `wasm32-wasi` to the name of the CI steps, so that it more clearly shows that an additional target is installed
> Add wasm32-wasi to the name of the CI steps

- playground/static/index.html
- playground/static/style.css
- playground/web_bindings/Cargo.toml
- playground/web_bindings/src/lib.rs
This PR resolves GH-34 by adding an extra tab where the context (and the packages) can be inspected (see screen-shot).
The styling of the playground is also improved by adding nicer buttons, a better layout for phone sized screens and a few icons here and there.
> GH-34: Add context inspector + better styling

- cli/src/main.rs
- parser/Cargo.toml
- parser/src/lib.rs
- parser/src/module.rs
- parser/tests/compilation_test.rs
- parser/tests/compilation_tests/invalid_module_invocation.mdmtest
- parser/tests/compilation_tests/invocation_with_named_arguments.mdmtest
- parser/tests/compilation_tests/invocation_with_unnamed_arguments.mdmtest
- parser/tests/compilation_tests/invocation_with_unnamed_then_named.mdmtest
- parser/tests/compilation_tests/invocation_without_arguments.mdmtest
Resolves: GH-32
Adds the enum MaybeArgs instead of Modulearguments to be able to handle when no valid arguments exists.
> GH-32: Add error checking for unnamed arguments after named arguments

- parser/src/lib.rs
- playground/static/index.html
- playground/web_bindings/src/lib.rs
This is a small increment to #50 and does the following:
1. Clarify the error message that appears on Nom errors (which normally shouldn't appear at all, but must be handled anyways)
2. Removes `Element` views from the playground; they aren't that useful and is a struggle to maintain. The `Ast` view may represent the same data as the `Element` does and more. The `Ast` view may show errors while the `Element` would fail and need a fall-back or force-unwrapping which are both bad
Resolves GH-32
> Fix deployment and clean up error handling

- .github/workflows/DeployPreview.yml
This PR changes `DeployPreview.yml` to not build the page if the pull request is closed. It is still important that the workflow runs, since it needs to do that to remove the preview playground page when the PR is closed.
> GH-66: Do not build pages when pull request is closed

- parser/src/lib.rs
- parser/tests/compilation_test.rs
- parser/tests/compilation_tests/heading_levels.mdmtest
- parser/tests/compilation_tests/headings_and_paragraphs.mdmtest
- parser/tests/compilation_tests/headings_in_blocks.mdmtest
- parser/tests/compilation_tests/headings_with_tags.mdmtest
Resolves: #44 
Adds headings in the parser. This allows syntax like ``# Title`` to be parsed as a "Heading1" node.
> GH-44: Add headings

- playground/static/index.html
This adds information about what the current branch is during a preview of a PR, together with a link to that PR.
Resolves #70
> GH-70: Add branch information in playground

- .github/workflows/DeployMain.yml
- .github/workflows/DeployPreview.yml
#66 aimed at adding preview deployment for pull request into the GitHub Pages Playground deployment. #67 implemented workflows responsible for that - then #69 added lots of `if` cases to ensure that the playground isn't actually built when the pull request is closed. This made the workflow less readable overall. This PR splits the DeployPreview workflow into two distinct jobs: `build-and-deploy` which deploys on new PRs/reopened PRs/synchronized PRs, and `teardown` which runs on closed PRs to remove the deployment. The `if` cases are only applied to the jobs overall and not within each job which improves readability. It also changes the default url (`modmark-org.github.io`) to our custom domain `modmark.org` for the automated message.
Resolves GH-66
> GH-66: Simplify preview workflow

- parser/Cargo.toml
- parser/src/or.rs
`or.rs` is a file which allows combining different parsers of different types in a way where all parsers are tested and the result of the first one which succeeds is returned. It added functions `or2` `or3` ... `or7` to support different amount of parsers, and even though the functions were simply delegating work to other functions, it was tedious and error-prone work to write ~55 lines for just one instance, where one mistake may make the result completely invalid.
This PR replaces the old hard-coded 6 functions by functions generated by macros. Now, there are `or`-functions for any amount of parsers from 2 to 26. I think this is much better since the automatic generation makes sure that there can't be mistakes due to carelessness when copy-pasting the function to add one argument, and …
> GH-22: Use macros in or.rs to avoid repeated code

- core/Cargo.toml
- core/src/context.rs
- core/src/element.rs
- core/src/error.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/std_packages.rs
- core/src/std_packages_macros.rs
This PR aims to restructure the native packages, those which are written in rust in the source code to Modmark, to use the same interface as external packages loaded from wasm. This is done mainly by changing `wasm_module: Module` in the `Package` struct to an enum holding two options, either the wasm module or a flag telling the core that the package is implemented natively.
Some work has already been done, and now all packages are under the same interface. We no longer have lots of `if name == "raw" {...}; if name == "parse_inline" {...} ...`, the native packages are in the same list as the normal packages and are searched for in the same way. Some macros has also been added to simplify the declaration of such native packages.
There is still some work to be done:
Resolves #82
> Unify structure for external, native and built-in packages

- core/src/context.rs
- core/src/lib.rs
- core/src/package.rs
This PR resolves #80. 
Comparing the memory footprint of the playground of this branch (left) to main (right) after 50 rerenders of an empty document you notice that the new version is still around 7-8mb while our current implementation has grown to 66mb.  
I got afraid that this issue would end up very hard to fix with proper web support without having to resort to recompiling all modules every time they are used. However, after a bit of digging in the `wasmer::js::module` I found that it seems like even though Wasmer requires the `Module::new` method to borrow a store it does not actually use it for anything. So we can create a dummy store when first compiling modules for web (and in the case of native platforms just use an Engine that we store in the context object) and then later …
> GH-80: Fix memory leaks

- parser/src/lib.rs
- parser/src/punct.rs
- parser/src/tag.rs
- parser/tests/compilation_tests/smart_punctuation_mixed_quotes.mdmtest
- parser/tests/compilation_tests/smart_punctuation_quotes.mdmtest
- parser/tests/compilation_tests/smart_punctuation_sequences.mdmtest
Resolves: #55 
This PR adds smart punctuation.
TODO:
> Add smart punctuation

- core/src/context.rs
- core/src/error.rs
- core/src/package.rs
Resolves #87 by introducing a new deserialization error type. A downside is that if the question mark operator is used on serde_json::Error it will always give the generic json error but since all errors are the same in serde_json I don't see another way to do it.
Here is an example if you break a module (table in this case):
> GH-87: Add specific deserialization error

- cli/Cargo.toml
- core/Cargo.toml
- core/build.rs
- core/src/std_packages_macros.rs
- playground/web_bindings/Cargo.toml
This PR adds support for disabling bundling of standard packages. There is now a feature `bundle_std_packages` which is enabled by default, which makes sure the packages are built and bundled. If you build either `cli` or `playground` with `--no-default-features`, it will be disabled and the packages will not be bundled.
Resolves #91
> GH-91: Add support for disabling the bundling of standard packages

- cli/src/main.rs
- core/src/context.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/std_packages.rs
- modules/README.md
- modules/html/src/example.json
- modules/html/src/main.rs
- playground/static/index.html
- playground/static/style.css
- playground/web_bindings/Cargo.toml
- playground/web_bindings/src/lib.rs
This PR aims at adding error handling for modules. A module may fail for multiple reasons, and the default behaviour shouldn't be that no part of the document can be evaluated just because one module fails. It may not be obvious why a module failed, especially if one module invokes other modules etc.
This implementation of error handling works on this fundamental concept:
* The `Context` has a `CompilationState`, which keeps the state of the document compilation, including what errors and warnings have occurred
To facilitate error reporting, these native modules have been added:
* `[error]` which adds an error to the current context, and takes optional arguments `source` and `target`
* `[warning]` which adds an warning to the current context, and takes optional arguments `source` and …
> Add error handling for modules

- parser/src/lib.rs
- parser/tests/compilation_tests/headings_with_tags.mdmtest
Resolves: #93 
This PR extends the functionality of headings to allow modules. This is done by using ``parse_paragraph_elements`` inside ``parse_heading``.
Example: ``# This heading has a cool equation: [math]x^2=4``
> GH-93: Allow modules in headings

- playground/static/example.mdm
- playground/static/main.js
This PR aims to clean up the JavaScript code in the playground a bit, increasing performance by disabling type coercion and disabling `console.log`ging things every compile. The PR also adds an example document, and when the playground is loaded, that document is loaded and the editor is changed into "Render HTML" mode.
Resolves GH-97
> GH-97: Clean up playground JS and add example document

- playground/static/index.html
Somehow, an unclosed `<div>` tag was introduced, along with a closing `</pre>` which doesn't have an opening `<pre>`. I don't know how that happened, but this PR aims to clean up the playground HTML by fixing that, along with changing the capitalisation to "ModMark Playground".
Resolves #97
> GH-97: Clean up playground HTML

- Cargo.toml
- core/src/std_packages.rs
- packages/math/Cargo.toml
- packages/math/src/main.rs
- packages/math/tests/test_import_html.json
- packages/math/tests/test_inline_html.json
- packages/math/tests/test_inline_latex.json
- packages/math/tests/test_multiline_html.json
- packages/math/tests/test_multiline_latex.json
- playground/static/example.mdm
This PR implements a `[math]` module, usable both inline and multi-line, with both `HTML` and `LaTeX` as output formats.
For the HTML output format, [mathjax](https://www.mathjax.org/) is imported by adding a `<script async src=...>` tag just before the math content. This can be disabled by giving `false` as the `import` argument, such as `[math import=false]$x^2$`. mathjax allows displaying of MathML in browsers which lacks native support for that. [latex2mathml](https://crates.io/crates/latex2mathml) is used to convert LaTeX to MathML when the output format is HTML, and since that natively supports both inline-style and block-style math, the `inline` parameter is carried over.
For the LaTeX output format, `$...$` is used for inline math, making sure to escape any `$` in the input by …
> GH-116: Add math module

- playground/static/expand_more.svg
- playground/static/style.css
This PR adds `-webkit-appearance: none;` to the `<option>` in the playground, which makes it look better on Safari on Mac. I think this is a simple improvement that is worth merging. See #120 for screenshots and more details. It also reformats the CSS file and removes a duplicate key `height` under the `#editor, #preview` selector. The duplicate key doesn't do anything and can thus be removed.
Resolves #120
> GH-120: Add -webkit-appearance: none;

- playground/static/example.mdm
This changes the example document to use `\[table]` instead of `[__text][[table]]`, which is probably less confusing for new users.
Resolves #122
> GH-122: Escape table module rather than passing it as text

- packages/code/src/example.json
- packages/code/src/main.rs
- packages/code/tests/test_inline.json
Resolves: #140 
Note that I chose to omit giving warnings for inline usage. The changes of interest should be line 88 to 95, the rest was done by ``cargo fmt``.
> GH-140: Fix HTML output from inline code modules

- core/src/lib.rs
- package-tests/Cargo.toml
- package-tests/tests/package_tests.rs
- packages/README.md
- packages/html/src/main.rs
- packages/latex/src/main.rs
- packages/table/src/main.rs
See issue #143. This PR resolves that issue by adding the conventions discussed there into `packages/README.md` and adds a test in `package-tests` which checks that these conventions are being met. Additionally, the convention test gives a warning if a package doesn't have any tests in it (but it doesn't fail the test). This PR also changes the current packages to follow the convention.
Resolves #143
> GH-143: Clarify and enforce package conventions

- core/src/lib.rs
- packages/table/src/example.json
- packages/table/src/main.rs
- packages/table/tests/test_all_border_html.json
- packages/table/tests/test_all_border_latex.json
- packages/table/tests/test_heading_html.json
- packages/table/tests/test_heading_latex.json
- packages/table/tests/test_horizontal_border_html.json
- packages/table/tests/test_horizontal_border_latex.json
- packages/table/tests/test_mixed_alignment_html.json
- packages/table/tests/test_mixed_alignment_latex.json
- packages/table/tests/test_no_strip.json
- packages/table/tests/test_outer_border_html.json
- packages/table/tests/test_outer_border_latex.json
- packages/table/tests/test_right_alignment_html.json
- packages/table/tests/test_right_alignment_latex.json
- packages/table/tests/test_strip.json
- packages/table/tests/test_vertical_border_html.json
- packages/table/tests/test_vertical_border_latex.json
This PR aims to resolve GH-94 by adding wanted improvements to the Table package. Here are the points listed, with my comments:
- *Works as expected, one backslash escapes the delimiter, two doesn't, three does etc*
- *There is an `alignment` argument which you can set to left/center/right or some combination of l/c/r, one character for each column, like ccr which would center the two first columns and right-align the third.*
- *Argument `borders` can be `all`/`horizontal`/`vertical`/`outer`/`none`. The options are self-explanatory. All but `none` implies `outer`*
- *Argument `header` can be `none` which has no special treatment or `bold` which is `th` in html and `textbf` in latex*
- *Argument `strip_whitespace` (true/false) controls stripping of whitespace*
~~This is a draft PR for now, …
> GH-94: Improve table package

- playground/build-playground.sh
- playground/static/compiler.js
- playground/static/main.js
Resolves GH-45. This PR adds support for the playground in Chromium browsers. This is done by instantiating the WASM module that contains the compiler inside of a web worker instead of the main thread.
> Playground: Add chromium support

- playground/static/compiler.js
- playground/static/main.js
This PR fixes two small problems introduced in #151:
- The worker JS has a switch with two branches on the same input where only one of them contains valid code; the invalid branch is removed
- Type coercion was enabled when comparing sequence numbers, this has now been removed
> GH-45: Fix problematic JS from GH-151

- core/src/error.rs
- core/src/lib.rs
- packages/html/src/main.rs
- packages/html/src/templates/html.css
- packages/html/src/templates/latex.css
- packages/html/tests/test_document.json
- playground/static/compiler.js
- playground/static/main.js
- playground/web_bindings/src/lib.rs
This PR  adds two CSS files for the html package, currently it just defaults to the one called `html.css`. Once variables and config is available #170 should be implemented. Also created a eval_no_document function in core that is now used by the playground to avoid getting html body and style tags.
- Resolves: GH-153.
> GH-153: Add default html styling

- core/Cargo.toml
- core/build.rs
- core/src/context.rs
- core/src/error.rs
- core/src/package.rs
- core/src/std_packages_macros.rs
This PR adds the feature `precompile_wasm` to `core`, which may be used when targeting `native` and using `bundle_std_packages`. When enabled, as a part of the build script which builds the packages, another step is added which runs the packages though the Cranelift compiler (which is the one we use in Wasmer), and saves that Cranelift-compiled module instead of the actual WebAssembly file. This file, that has already been compiled, is referred to by me as "precompiled" and is using the `.wir` file format (I made that up, Wasmer Internal Representation). The main benefit this has is improving start-up time for the ModMark binary, since Wasmer doesn't have to compile the WebAssembly modules.
Due to technical limitations in Cargo and to developer wrongdoings in Wasmer, the actual …
> GH-173: Add `precompile_wasm` feature

- cli/src/main.rs
- cli/src/package.rs
- core/src/context.rs
- core/src/error.rs
- core/src/lib.rs
- core/src/std_packages.rs
- core/src/std_packages_macros.rs
- parser/src/config.rs
- parser/src/lib.rs
- playground/web_bindings/src/lib.rs
This PR adds the `[config]` module. This isn't a native module nor an external module, it is a parser module which is handled at the parsing step immediately. Currently, there is support for `import`, `hide` and `set` statements.
To use the config module, put a multiline `[config]` module at the very top of the document. `[config]` modules are not allowed anywhere else. Thereafter, each line of the module body is a config statement. There are three types of statements described below, and here is an example of a config module expression:
```
[config]
hide table
import bettertable
set bettertable_colours gray white gray black
```
Import statements come in three flavours:
```
import foo
import bar using a, b, c
import baz hiding x, y, z
```
They import the given package, possibly only …
> Add `config`uration module

- packages/html/src/main.rs
- packages/html/tests/test_math.json
- packages/html/tests/test_math_empty.json
- packages/html/tests/test_math_interspersed.json
- packages/latex/src/main.rs
- packages/latex/tests/test_math.json
- packages/latex/tests/test_math_empty.json
- packages/latex/tests/test_math_interspersed.json
This PR resolves GH-118 by adding support for math tags `$$` containing text only, by taking the text and making a `math` module containing the very same text. More detailed explanation on why to delegate it to the `math` module rather than implementing support for it in the language packages directly can be found in the [original issue](https://github.com/modmark-org/modmark/issues/118). The support is added to both the HTML and LaTeX language packages. Even though it could in theory be implemented in the `math` package, I think it makes more sense to add them to the language packages which should be responsible for handling all tags.
All text from within the math tags gets concatenated, and that is the input to the `math` module. Since the tags are non-recursive, only text and modules …
> GH-118: Delegate text-only math tags to math module

- cli/Cargo.toml
- cli/src/main.rs
- cli/src/package.rs
Resolves GH-127. This PR adds a `--registry` flag (shorthand `-r`) which lets the user specify an URL to a different registry that the user wants to use rather than the default registry we provide. This is achieved by adding a `registry: String` field to the PackageManager which holds the registry URL, and constructing the `Context` with a `PackageManager` created after the arguments has been parsed. It changes the `Lazy<...<Context<PackageManager>>>` for `OnceCell<...<Context<PackageManager>>>` since we can't just create a `Context` immediately; we need to parse the arguments before creating one. At all places where the `Context` is used, it is forcefully unwrapped since it is guaranteed to be set immediately after parsing the arguments (or, if it fails to create a `Context`, it will …
> GH-127: Add flag to choose a different registry

- core/src/context.rs
- core/src/error.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/std_packages.rs
- core/src/std_packages_macros.rs
- package-tests/tests/package_tests.rs
- packages/code/src/main.rs
- packages/code/tests/test_defaults.json
- packages/code/tests/test_inline.json
- packages/code/tests/test_java.json
- packages/layout/src/main.rs
- packages/list/src/lib.rs
- packages/list/src/main.rs
- packages/math/src/main.rs
- packages/table/src/main.rs
- playground/static/main.js
This PR resolves GH-79 by adding a `type` field to `ArgInfo` and changing `default` from being `Option<String>` to `Option<Value>` (note that `type` is written `r#type` in Rust since `type` is a reserved keyword). It is an enum which can be deserialised from one of the following strings:
* `Integer`/`int`/`integer`/`i64` for the `i64` Rust data type, serialised as a Json Number
* `Unsigned integer`/`uint`/`unsigned_integer`/`u64` for the `u64` Rust data type, serialised as a Json number
* `Float`/`float`/`number`/`f64` for the `f64` Rust data type, serialised as a Json number
* `String`/`string` for the `String` Rust data type, serialised as a Json string. If the field is absent, this is the default value.
When reading an argument that is of a specific type, the string input is parsed …
> Add different argument data types

- playground/static/main.js
- playground/static/style.css
Resolves GH-193 with a splash of color for the package view.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
<td>
</td>
</tr>
> Improve package view styling

- core/src/context.rs
RuntimeError did not seem to be typed in any meaningful way so unfortunately I think the best way to do this might just be a string comparison.
Resolves #198
> GH-198: Ignore runtime errors where exit code was 0

- packages/files/src/main.rs
- packages/latex/src/main.rs
- packages/latex/tests/test_document.json
Resolves #209, resolves #179 
This PR adds transforms to LaTeX for all modules inside the files package.
The [image] module also includes `caption`, `label` and `width` as arguments. I'm a little unsure to optimally handle the user not specifying `width`, and what it should default to in that case. Currently it defaults to "width=1.0\textwidth".
> Improve files package

- core/Cargo.toml
- core/build.rs
- core/src/context.rs
- core/src/element.rs
- core/src/error.rs
- core/src/lib.rs
- core/src/schedule.rs
- core/src/std_packages.rs
- core/src/std_packages_macros.rs
- core/src/variables.rs
- playground/web_bindings/Cargo.toml
- playground/web_bindings/src/lib.rs
This PR adds a new struct `Schedule` to `Core`. This struct keeps track of all elements there are and may be polled to get the next element it think should be evaluated. 
The code we had previously to evaluate a document was this:
```rs
pub fn eval_elem<T, U>(root: Element) -> Result<String, CoreError> {
use Element::{Compound, Module, Parent};
match root {
Compound(children) => {
let mut raw_content = String::new();
for child in children {
raw_content.push_str(&eval_elem(child, ctx, format)?);
}
Ok(raw_content)
}
Module { .. } | Parent { .. } => {
let either = ctx.transform(&root, format)?;
match either {
Left(elem) => eval_elem(elem, ctx, format),
Right(res) => Ok(res),
}
}
}
}
```
*Note that some details not important to getting the point across are omitted from this and upcoming code …
> Add Scheduler to Core

- playground/static/style.css
Resolves: #197 
It seems the issue was caused by overwriting the overflow property to "auto" for the editor element. Ace sets this to "hidden" otherwise.
> GH-197: Fix y-overflow in playground

- core/src/context.rs
- core/src/error.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/package_store.rs
- packages/files/src/main.rs
Resolves: #128 
TODO: 
To try it out you can use the `[include]` module, which I've changed to use "any" as output format. 
Collisions seem to work as intended. I tested this by adding a `[hello] -> any` transform and then importing hello from the catalog.
> Add any as special output format

- package-tests/tests/package_tests.rs
- parser/src/module.rs
- parser/tests/compilation_tests/inline_module.mdmtest
- parser/tests/compilation_tests/invocation_with_named_arguments.mdmtest
Resolves GH-234.
Now, this document contains two module expressions and some text:
```
[foo]()
abc
[foo]()
```
whereas it previously was one multiline module expression and no text.
This also parses: `[foo some-key=some-value]` whereas it previously didn't.
> GH-234: Parser adjustments

- cli/Cargo.toml
- cli/src/error.rs
- cli/src/main.rs
Resolves GH-211 by removing the debouncing file watcher in favour of a simpler one. A bit of regression since I think we are at risk of doing multiple unnecessary recompilations back-to-back in some cases. But, it should not be to bad and I rather have something semi-optimal that works then something broken.
> Remove debounce watcher

- core/src/context.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/package_store.rs
- core/src/schedule.rs
- core/src/std_packages.rs
- core/src/std_packages_macros.rs
- packages/files/src/main.rs
- packages/flow/src/main.rs
- packages/layout/src/main.rs
- packages/list/src/main.rs
- packages/table/src/main.rs
This PR resolves GH-225 by adding an optional field `unknown-content` to the manifest for a transform. Setting this field to true ensures that that module is executed before any module which has that field set to false.
Take this as an example:
```
[push-list abc] a
[inline_content]
[push-list abc] b
[read-list abc]
```
We have three modules, `push-list`, `inline_content` and `read-list`. We know that the scheduler will ensure `push-list` occurs before `read-list`, but the scheduler doesn't know anything about `inline_content` so it may schedule it whenever it sees fit. If it schedules it before evaluating `read-list`, the dependency will be picked up as expected but if it schedules it later, `read-list` would already have been executed.
This PR changes it so that `inline_content` in this …
> GH-225: Implement `unknown_content` for transforms

- core/src/context.rs
- core/src/element.rs
- core/src/error.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/schedule.rs
- core/src/std_packages.rs
- core/src/std_packages_macros.rs
- core/src/variables.rs
This PR implements:
* A `VariableStore` which lives in the `Context` struct and keeps all shared state.
* Six new modules: `const-read`, `const-decl`, `list-push`, `list-read`, `set-add`, `set-read` for manipulating variables stored in the shared state.
* A way of accessing the variables in packages by using WASI env variables `env::var("<TYPE>_<NAME>=<VALUE>")`.
Feel free to try out, I've left a sample document at the bottom of the PR.
* Currently we allow two variables to have the same name as long as they have different types. This is a bit unconventional and complicates the code somewhat. And most importantly it might cause some confusions for package authors because if they declare a variable `"variables: { "foo": {type: "const", access: "read"}}` they must remember to use key …
> Implement variable store

- packages/files/src/main.rs
- packages/latex/src/main.rs
- packages/latex/tests/test_bold.json
- packages/latex/tests/test_document.json
- packages/latex/tests/test_italic.json
- packages/latex/tests/test_strikethrough.json
- packages/latex/tests/test_subscript.json
- packages/latex/tests/test_superscript.json
- packages/latex/tests/test_underlined.json
- packages/latex/tests/test_verbatim.json
- packages/link/src/main.rs
- packages/link/tests/latex_test_label.json
- packages/link/tests/latex_test_nolabel.json
- packages/list/src/lib.rs
- packages/list/src/main.rs
- packages/table/src/main.rs
- packages/table/tests/test_all_border_latex.json
- packages/table/tests/test_caption_label_latex.json
- packages/table/tests/test_caption_latex.json
- packages/table/tests/test_heading_latex.json
- packages/table/tests/test_horizontal_border_latex.json
- packages/table/tests/test_label_latex.json
- packages/table/tests/test_mixed_alignment_latex.json
- packages/table/tests/test_outer_border_latex.json
- packages/table/tests/test_right_alignment_latex.json
- packages/table/tests/test_vertical_border_latex.json
This PR resolves GH-248 by adding an `imports` set to store what imports are needed. Entries are added to this set via the `[set-add]` module, and a macro was made to simplify the use of this:
```rust
macro_rules! import {
($e:expr) => {json!({"name": "set-add", "arguments": {"name": "imports"}, "data": $e})}
}
```
The macro is similar to the `raw!` macro, but generates a `set-add` instead.
The transforms that relies on imports have been updated to push their imports to the set. This applies to all packages.
All previously hardcoded packages are now removed from the prelude in `__document`, and when transforming that, the imports are read and parsed as a JSON array (or as an empty array if the key doesn't exist), and a prelude is created with those imports.
This PR is ready for review …
> Use set for LaTeX imports

- packages/flow/src/main.rs
- packages/flow/tests/test_list_contains.json
- packages/flow/tests/test_list_contains_all.json
- packages/flow/tests/test_list_contains_any.json
- packages/flow/tests/test_list_contains_none.json
- packages/flow/tests/test_list_defined.json
- packages/flow/tests/test_list_does_not_contain.json
- packages/flow/tests/test_list_undefined.json
- packages/flow/tests/test_set_contains.json
- packages/flow/tests/test_set_contains_all.json
- packages/flow/tests/test_set_contains_any.json
- packages/flow/tests/test_set_contains_none.json
- packages/flow/tests/test_set_defined.json
- packages/flow/tests/test_set_does_not_contain.json
- packages/flow/tests/test_set_undefined.json
This PR resolves #250 by adding three new modules, `[if-const]`, `[if-list]` and `[if-set]`. They all have he same general syntax, `[if-<type> <variable> [check] [value] [case-sensitive]]` where `<type>` is the type (`const`/`list`/`set`), `<variable>` is the name of the variable to check, `[check]` is the way to check the variable (like the operator) and `[value]` is the value to check against. `[case-sensitive]` is set to `case-sensitive` by default and affects all string comparisons.
`[if-const]` has these checks:
* **defined** succeeds if the constant is defined (default)
* **undefined** succeeds if the constant is undefined
* **equals** succeeds if the constant value equals *value*
* ~~differs-to~~ **differs-from** succeeds if the constant value differs from *value*
Here are some …
> Variable based conditional compilation

- packages/html/src/main.rs
- packages/html/tests/test_document.json
> GH-252: Add `<meta charset="UTF-8">` to html template

- packages/layout/src/main.rs
- packages/layout/tests/newline_latex.json
> GH-258: Add `{}` to not consume arguments to newline `\\`

- packages/flow/src/main.rs
- packages/flow/tests/test_comment.json
- packages/flow/tests/test_hide.json
Resolves GH-264 by adding `[hide]` and `[comment]` modules, both of which just doesn't do anything with its input
> GH-264: Add `[hide]` and `[comment]` modules

- package-tests/tests/package_tests.rs
Resolves GH-266 by placing build output in `$CARGO_TARGET_TMPDIR/<package name>` rather than inside the `packages` folder. `CARGO_TARGET_TMPDIR` is, according to cargo docs, "only set when building [integration test](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#integration-tests) or benchmark code. This is a path to a directory inside the target directory where integration tests or benchmarks are free to put any data needed by the tests/benches. Cargo initially creates this directory but doesn’t manage its content in any way, this is the responsibility of the test code". This means that it is fine to use that as the out directory for packages.
Running the tests the first time may take a little longer than previously, since it has to re-build everything the first time, but …
> GH-266: Set alternative out dir for package-tests

- Cargo.toml
- core/src/std_packages.rs
- packages/bibliography/Cargo.toml
- packages/bibliography/customizing_your_bibliography.md
- packages/bibliography/src/main.rs
- packages/bibliography/tests/test_bibliography.json
- packages/bibliography/tests/test_bibliography_hidden.json
- packages/bibliography/tests/test_bibliography_unused_hidden.json
- packages/bibliography/tests/test_bibliography_unused_shown.json
- packages/bibliography/tests/test_bibliography_unused_shown_html.json
- packages/bibliography/tests/test_bibliography_unused_shown_latex.json
- packages/bibliography/tests/test_cite_no_note.json
- packages/bibliography/tests/test_cite_with_note.json
This PR resolves GH-254 by adding a bibliography package. The package generates bibliographies, surprise surprise.
I think I am more or less done with this package, but it may have some rough edges, so please come with comments if you have any. There are two new modules intended for use; `[cite [note]] <name>`  will cite a source from the bibliography by its name, optionally allowing a note such as page numbers, and `[bibliography [style] [file]] <database>` which imports a BibTeX or Hayagravia Yaml file and uses that to create a bibliography and resolve previous citations. The BibLaTeX (or Yaml) content may be in a file (where the filename is passed as argument), or inserted as the body of the module.
Example document:
```
John MacFarlane [cite "p. 22"] djot released a product
called …
```
> GH-254: Add bibliography package

- core/src/context.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/schedule.rs
- core/src/std_packages_macros.rs
- packages/html/src/main.rs
- packages/latex/src/main.rs
This PR resolves GH-275. The problem was that `$$x^2$$` gets represented as `__math { __text "x^2" }`, and if `__text` is evaluated before `__math`, it won't work since `__text` will be replaced with just a raw string. The core issue is that we have no dependency saying that `__math` must be evaluated before `__text`, as is the case here to get correct output (and it is also the case with `__verbatim`). This PR adds an option to the transforms in the manifest `evaluate-before-children`, default to `false`, that when true, if a parent is detected with the corresponding name, it will be guaranteed to be evaluated before its children. This PR also sets this flag for `__math` for HTML/LaTeX and `__verbatim` for LaTeX (unimplemented in HTML). This flag should only be used when the parent …
> GH-275: Add `evaluate-before-children` option to transforms

- cli/src/package.rs
- core/src/package_store.rs
This PR resolves GH-280 by making Core check if the file name ends in `.wasm` and, if it doesn't, append it to the file name. This means that regardless if the user specifies `import foo` or `import foo.wasm`, Core will give a `ResolveTask` saying "*Resolve the file `foo.wasm`*" and the resolvers themselves doesn't have to add the extension. This means that more logic has been moved from the split-up resolvers to the same Core they both use, making unsynchronized behaviour more unlikely.
> GH-280: Append `.wasm` to local packages in modmark-core

- cli/Cargo.toml
> GH-292: Bump warp to 0.3.5

- playground/web_bindings/src/web_resolver.rs
Resolves: #294 
This PR solves the CORS problem by using a CloudFlare worker as a proxy, which adds the necessary `Access-Control-Allow-Origin` header. I used the code at https://developers.cloudflare.com/workers/examples/cors-header-proxy with the addition of manually sending another request to a new URL if the response status was 302.
> Use proxy to fetch packages from catalog in playground

- .github/workflows/DeployMain.yml
- .github/workflows/DeployPreview.yml
- .github/workflows/RustCI.yml
- README.md
- cli/Cargo.toml
- core/Cargo.toml
- core/build.rs
- website/web_bindings/Cargo.toml
This PR resolves GH-311, and enables both optimizing bundled packages and precompiling bundled packages when building CLI by default. Previously, the packages weren't pre-compiled by default hehe...
Anyhow, these are the binary sizes, compiled on macOS 13.3.1 on M1:
| Type | Size (bytes) |
|-----|-------------|
| No optimization, no precompilation | 49 703 189 |
| Optimized, no precompilation | 44 337 653 |
| No optimization, precompiled | 65 218 869 |
| Optimized, precompiled (default) | 58 531 509 |
These features can be turned on and off with features, for example `cargo build --release --no-default-features --features modmark_core/optimize_bundled_packages` will run wasm-opt but not pre-compile the packages with Cranelift. The wasm-opt feature is available for both web and native …
> GH-311: Run wasm-opt on bundled packages

- cli/src/file_access.rs
- core/src/context.rs
- core/src/error.rs
- core/src/lib.rs
- core/src/package.rs
- core/src/package_store.rs
- core/src/std_packages.rs
- core/src/std_packages_macros.rs
- packages/files/src/main.rs
- packages/html/src/main.rs
- packages/latex/src/main.rs
- parser/src/lib.rs
- website/src/Buttons.tsx
- website/src/FsTree.tsx
- website/src/Homepage.tsx
- website/src/PackageDocs.tsx
- website/src/PackageDocsPage.tsx
- website/src/Playground.tsx
- website/src/Preview.tsx
- website/src/compilerTypes.ts
- website/src/main.tsx
This PR resolves GH-307 and resolves GH-208 by adding an enum keyed `type` to `Transform`:
```rust
#[serde(rename_all = "kebab-case")]
pub enum TransformType {
#[default]
Module,
InlineModule,
MultilineModule,
Parent,
#[serde(alias = "*")]
Any,
}
```
Then, before executing a transform, the element type is checked such that if Module is specified and the element is a Parent, it will be transformed to an error node instead. This is in line with argument type checks, whereas the compiler sometimes doesn't execute a transform if it is doomed to fail, but rather early returns a nicer error message.
It is unclear which of the current transforms should have what type, but since `Module` is default, all the language packages have been changed so many transforms (such as `__document`, …
> Add ArgumentType

- packages/files/src/main.rs
Resolves: #289
This PR also removes usage of the `raw!` macro.
> Fix centering for images

- packages/html/Cargo.toml
- packages/html/src/main.rs
- packages/html/tests/test_bold.json
- packages/html/tests/test_italic.json
- packages/html/tests/test_strikethrough.json
- packages/html/tests/test_subscript.json
- packages/html/tests/test_superscript.json
- packages/html/tests/test_underlined.json
- packages/latex/Cargo.toml
- packages/latex/src/main.rs
- packages/latex/tests/test_verbatim.json
This PR resolves GH-313 by changing the type of the following transforms from `Parent` to `Any`:
* `__bold`
* `__italic`
* `__superscript`
* `__subscript`
* `__strikethrough`
* `__underlined`
* `__verbatim`
This applies to both the HTML and LaTeX package. Special care is taken for `__verbatim` so that it becomes `\verb||`/`<code>` when invoked inline, and `\begin{verbatim}`/`<pre>` when invoked multiline. This PR also resolves an issue where too many characters were escaped in `\verb`, so that ` ``hello_world`` ` was rendered `hello\_world`
This PR is ready for review immediately. This behaviour is also needed for writing the thesis.
> GH-313: Allow some parents to be invoked as modules

- packages/latex/src/main.rs
`\textbackslash{}` is currently `\textbacklash{}`. This PR fixes that typo.
> GH-58: Fix typo in textbackslash

- packages/list/src/lib.rs
#297 accidentally removed a space here after `\item`. This PR adds that space back =)
> GH-296: Add space after '\item'

- packages/files/src/main.rs
Simple fix, labels like `modmark_example` were getting converted to `modmark\_example` due to inline_content instead of raw.
> GH-210: Change label in LaTex to raw to avoid escaping

- packages/table/src/main.rs
- packages/table/tests/test_caption_label_latex.json
- packages/table/tests/test_caption_latex.json
- packages/table/tests/test_label_latex.json
Resolves: #331 
As the PR name indicates it also moves the label, because it seems to be more common that way.
> GH-331: Move label and caption for tables

- packages/code/src/main.rs
> GH-343: Avoid producing newline at the end of LaTeX highlighting

- website/src/Gist.tsx
- website/src/Playground.tsx
- website/src/gist.ts
Resolves GH-350
This PR supports loading gists with multiple files. If the gist only contains 1 file (and the filename ends with .mdm), that file will be loaded (as previous), but if it contains multiple files, the file named `main.mdm` is loaded while the others are added to the virtual file system.
This PR also changes some logic within `getGistById`. That function previously returned the Gist as a string and if any errors occur, returns `null`. Now, it can't return `null` but rather throws on network errors. If a logic error occurs, let's say that there are no `.mdm` files or that the gist contains multiple files but no one named `main.mdm`, it will rather return an appropriate error string to be loaded into the editor (and not throw).
Previous gists will be unaffected. When the PR …
> GH-350: Support loading multiple files from Gist

- packages/list/src/lib.rs
This PR resolves GH-356 by adding empty brackets after the `\item` command in LaTeX.
Now, this example compiles to valid LaTeX code, whereas it didn't previously:
```
[list]
* foo
* \[bar]
```
> GH-356: Add empty brackets after item in LaTeX

- parser/src/punct.rs
This PR resolves GH-362 by checking that the index `try_smart_sequence` is going to split at is actually a char boundary. If not, it tries to backtrack not only one but two bytes, and if not, tries to backtrack three bytes etc.
You can try this out by doing `\😀` in the playground. Previously, the compiler would crash (and the status would be stuck at Compiling...), but now it works as expected. This is the code handling the smart sequences `...`, `--` and `---`, so you can try them out to see that they have not been broken. There might be better implementations of this, but I think this would be sufficient.
> GH-362: Check for char boundary before truncating

- packages/bibliography/Cargo.toml
- packages/bibliography/src/main.rs
- packages/bibliography/src/multicolumn.css
- packages/bibliography/src/singlecolumn.css
- packages/bibliography/tests/test_bibliography_hidden.json
- packages/bibliography/tests/test_bibliography_unused_hidden.json
- packages/bibliography/tests/test_bibliography_unused_shown.json
- packages/bibliography/tests/test_bibliography_unused_shown_html.json
- packages/bibliography/tests/test_bibliography_unused_shown_latex.json
This PR resolves GH-363 by improving the bibliography in several ways. As discussed in the issue, this PR makes the bibliography more language-agnostic again, by:
* Adding `output=table|plain*` which can be used to print the output in a table format, for output formats which has table implemented, while allowing just outputting in plain-text for output formats which doesn't have tables
* Adding `specialization=enable*|disable` to enable or disable specialization (where HTML and LaTeX output gets special treatment)
* Adding `styling=all|bold|italic|url|target` (zero or more can be enabled) which allows the bibliography to style only parts that are possible to style, so that one could disable bold styling for output languages not supporting bold, or URL for languages that doesn't have URLs. …
> GH-363: Improve bibliography

- core/src/context.rs
- website/web_bindings/Cargo.toml
- website/web_bindings/src/lib.rs
This PR adds a field `ID` to `JsonEntry` variants `Parent` and `Module`. This ID is guaranteed to be unique (per compilation cycle), so that if you get some data with ID 325, you know that no other modules or parents generated during the entire compilation cycle has ID 325. Moreover, this is "simulated" in the JSON output view with random numbers in the range `5 000-500 000`, to show that you can't depend on any property of IDs other than that they are unique. In practice, when Core is assigning IDs when compiling a document, they are assigned sequentially from 100, but keep in mind that it is undetermenistic what parts of the document is evaluated when, so this isn't dependable. When deserializing JsonEntries, IDs are discarded, and are re-assigned when serializing the entries again. …
> GH-370: Add unique IDs

- packages/plot/src/main.rs
- packages/plot/src/plots.rs
- packages/plot/src/utils.rs
Resolves GH-376 by adding latex support to the plot package. The PR also fixes two bugs: html output for captions and integer overflow (Carl must of missed it since only debug builds cause panic on integer overflow in Rust)
> LaTeX support in plot package

- website/src/Playground.tsx
It works as it is right now but needs some polish.
- Native modules like "__bold" are shown in the list, do we want to filter transforms that start with __?
- Right now it simply removes all duplicate froms, an alternative would be to only show autocomplete for transforms that go to the currently selected output format. However I feel like that might be bad as you often want an HTML preview and then switch to LaTeX later and then the modules might change. Not sure about the best way to go about it.
- ~~Every single change to the text in the playground currently triggers the useEffect which means we are disposing of the model and rebuilding it very often. Obviously needs to be fixed.~~ - Fixed in later commit
> GH-374: Add autocomplete for modules
